import sharp from 'sharp';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import * as allIcons from 'simple-icons';
await mkdir('build', { recursive: true });
const logo = await readFile('public/logo.png');
await sharp(logo).resize(1024, 1024).png().toFile('build/icon.png');
await sharp(logo).resize(192, 192).png().toFile('public/icon.png');
const png = await sharp(logo).resize(256, 256).png().toBuffer();
const header = Buffer.alloc(22);
header.writeUInt16LE(1, 2); header.writeUInt16LE(1, 4);
header.writeUInt16LE(1, 10); header.writeUInt16LE(32, 12);
header.writeUInt32LE(png.length, 14); header.writeUInt32LE(22, 18);
await writeFile('build/icon.ico', Buffer.concat([header, png]));
const names = ['siNodedotjs', 'siPython', 'siOpenjdk', 'siGo', 'siRust', 'siApachemaven', 'siYarn', 'siPnpm', 'siElectron', 'siApple', 'siLinux', 'siGradle', 'siUv', 'siTypescript', 'siJavascript', 'siKotlin', 'siVuedotjs', 'siCplusplus', 'siC', 'siSwift', 'siPhp', 'siRuby', 'siDotnet', 'siDart', 'siHtml5', 'siCss', 'siGnubash'];
const icons = Object.fromEntries(names.map(name => { const { title, hex, path } = allIcons[name]; return [name, { title, hex, path }]; }));
await writeFile('src/shared/brand-icons.json', JSON.stringify(icons));
const technologyNames = { TypeScript: 'siTypescript', JavaScript: 'siJavascript', Python: 'siPython', Go: 'siGo', Rust: 'siRust', Java: 'siOpenjdk', Kotlin: 'siKotlin', Vue: 'siVuedotjs', 'C++': 'siCplusplus', C: 'siC', 'C#': 'siDotnet', Swift: 'siSwift', PHP: 'siPhp', Ruby: 'siRuby', Dart: 'siDart', HTML: 'siHtml5', CSS: 'siCss', Shell: 'siGnubash' };
await writeFile('src/shared/technology-icons.json', JSON.stringify(Object.entries(technologyNames).map(([name, key]) => {
  const icon = allIcons[key];
  return { name, aliases: [], sourceUrl: icon.source, data: Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="#${icon.hex}"><path d="${icon.path}"/></svg>`).toString('base64') };
})));
